defaults:
- /hydra_config/verl-0_7_0/default
- _self_
display_name: Ministral-3-3B-Instruct-2512-BF16 GRPO RLVR LoRA Fine-Tuning
version: 2.0.1
instance_types:
- ml.p5.48xlarge
- ml.p4de.24xlarge
run:
  model_type: verl
  name: verl-grpo-rlvr-ministral-3-3b-instruct-lora
  results_dir: ${base_results_dir}/${.name}
trainer:
  devices: 8
  num_nodes: 1
ray_cluster:
  head_node:
    cpu: '16'
    cpuLimit: null
    gpu: '0'
    memory: 32Gi
    memoryLimit: null
  worker_nodes:
    cpu: '48'
    cpuLimit: null
    gpu: '8'
    memory: 144Gi
    memoryLimit: null
    replicas: 1
training_config:
  algorithm:
    adv_estimator: grpo
    norm_adv_by_std_in_grpo: true
  actor_rollout_ref:
    hybrid_engine: true
    nccl_timeout: 600
    actor:
      strategy: fsdp2
      use_kl_loss: true
      kl_loss_coef: 0
      ppo_micro_batch_size_per_gpu: 8
      ppo_max_token_len_per_gpu: 32768
      optim:
        lr: 1.0e-05
      fsdp_config:
        strategy: fsdp2
        optimizer_offload: false
        param_offload: false
        wrap_policy:
          transformer_layer_cls_to_wrap: &id001
          - MistralDecoderLayer
    ref:
      fsdp_config:
        param_offload: true
        strategy: fsdp2
        wrap_policy:
          transformer_layer_cls_to_wrap: *id001
    rollout:
      name: vllm
      tensor_model_parallel_size: 2
      prompt_length: 1024
      response_length: 2048
      max_num_batched_tokens: 8192
      enable_chunked_prefill: true
      merge_lora_for_inference: true
    model:
      path: mistralai/Ministral-3-3B-Instruct-2512-BF16
      trust_remote_code: false
      enable_gradient_checkpointing: true
      use_remove_padding: true
      lora_rank: 32
      lora_alpha: 64
      target_modules: all-linear
      exclude_modules: .*visual.*
  trainer:
    merge_lora_on_final_save: true
    save_freq: 20
    logger:
    - console
    project_name: verl-grpo-rlvr
    experiment_name: ministral-3-3b-instruct-lora
    total_epochs: 1
    resume_mode: resume_path
    default_local_dir: /opt/ml/model
  data:
    max_prompt_length: 1024
    max_response_length: 2048
    train_val_split_ratio: 0.9
    shuffle: false
    return_raw_chat: true
  mlflow:
    run_id: ''
    tracking_uri: ''
  reward_manager:
    _target_: verl.trainer.config.config.RewardManagerConfig
    source: register
    name: prime
  custom_reward_function:
    lambda_arn: ''
    path: ''
    name: ''
  reward_model:
    reward_manager: naive
    enable: false
    strategy: fsdp2
    launch_reward_fn_async: true
    rollout:
      name: vllm
      gpu_memory_utilization: 0.5
    model:
      input_tokenizer: mistralai/Ministral-3-3B-Instruct-2512-BF16
