defaults:
  - /hydra_config/verl/default
  - /hydra_config/verl/algorithm/grpo
  - /hydra_config/verl/actor/default
  - /hydra_config/verl/ref/default
  - /hydra_config/verl/critic/default
  - /hydra_config/verl/rollout/vllm
  - /hydra_config/verl/actor_rollout_ref/default
  - /hydra_config/verl/trainer/default
  - /hydra_config/verl/data/default
  - /hydra_config/verl/reward_model/default
  - /hydra_config/verl/ray_cluster/default
  - /hydra_config/verl/peft/lora
  - /hydra_config/verl/reward/rlaif
  - /hydra_config/verl/model_config/gpt-oss-120b
  - _self_

display_name: GPT OSS 120B GRPO RLAIF Fine-Tuning with LoRA
version: 1.1.0
instance_types:
- ml.p5e.48xlarge
- ml.p5en.48xlarge
run:
  name: verl-grpo-gpt-oss-120b-lora
trainer:
  num_nodes: 1
training_config:
  actor_rollout_ref:
    actor:
      ppo_max_token_len_per_gpu: 32768
      optim:
        lr: 1.0e-05
    ref:
      log_prob_micro_batch_size_per_gpu: 16
      log_prob_max_token_len_per_gpu: 32768
    rollout:
      prompt_length: 1024
      log_prob_micro_batch_size_per_gpu: 16
      log_prob_max_token_len_per_gpu: 32768
      enable_chunked_prefill: true
      layered_summon: false
      merge_lora_for_inference: true
    model:
      path: openai/gpt-oss-120b-bf16
      attn_implementation: kernels-community/vllm-flash-attn3
      target_parameters:
      - mlp.experts.gate_up_proj
      - mlp.experts.down_proj
  trainer:
    experiment_name: phase_2
    resume_mode: resume_path
    resume_from_path: ''
  data:
    max_prompt_length: 1024
    max_response_length: 4096
    val_batch_size: null
    chat_template_kwargs:
      reasoning_effort: medium
  critic:
    model:
      tokenizer_path: openai/gpt-oss-120b-bf16
    use_dynamic_bsz: false
  reward_model:
    model:
      input_tokenizer: openai/gpt-oss-120b-bf16
      path: sfairX/FsfairX-LLaMA3-RM-v0.1
    use_dynamic_bsz: false
    reward_kwargs:
      reward_fn_name: llmj
      kwargs:
        llmj_prompt_template_path: /opt/ml/code/verl/summarize.jinja
        model_id: bedrock/deepseek.v3-v1:0
        num_retries: 5
        range:
        - 0.0
        - 1.0
        sampling_params:
          top_p: 0.9
          temperature: 0.0
          max_completion_tokens: 2048
          reasoning_effort: null
        max_workers: 100
        aws_region_name: null
  custom_reward_function:
    path: ''
    name: ''
ray_cluster:
  worker_nodes:
    replicas: 1
