defaults:
  - /hydra_config/llmft/default
  - /hydra_config/llmft/model_config/qwen-2-5-14b-instruct
  - /hydra_config/llmft/peft/lora
  - /hydra_config/llmft/algorithm/dpo
  - /hydra_config/llmft/datasets/default_dpo_fft
  - /hydra_config/llmft/strategy/fsdp_peft
  - _self_

display_name: "Qwen 2.5 14B Direct Preference Optimization on GPU, 4K sequence length"
version: "1.2.0"
instance_types: ['ml.p4de.24xlarge', 'ml.p4d.24xlarge', 'ml.p5.48xlarge', 'ml.g5.48xlarge']

run:
  name: qwen-2d5-14b

training_config:
  model_config:
    model_name_or_path: "Qwen/Qwen2.5-14B-Instruct"
    model_save_name: SageMaker/Qwen2.5-14B-Instruct-Lora
  training_args:
    merge_weights: true

elastic_policy:
  is_elastic: false
  min_nodes: 1
  max_nodes: 16
  use_graceful_shutdown: true
  scaling_timeout: 600
  graceful_shutdown_timeout: 600

scale_config:
  1:
    trainer:
      num_nodes: 1
    training_config:
      training_args:
        train_batch_size: 128
        micro_train_batch_size: 2
        learning_rate: 0.0002828
  2:
    trainer:
      num_nodes: 2
    training_config:
      training_args:
        train_batch_size: 128
        micro_train_batch_size: 2
        learning_rate: 0.0002828
  4:
    trainer:
      num_nodes: 4
    training_config:
      training_args:
        train_batch_size: 128
        micro_train_batch_size: 2
        learning_rate: 0.0002828
  8:
    trainer:
      num_nodes: 8
    training_config:
      training_args:
        train_batch_size: 128
        micro_train_batch_size: 2
        learning_rate: 0.0002828
  16:
    trainer:
      num_nodes: 16
    training_config:
      training_args:
        train_batch_size: 128
        learning_rate: 0.0002828
