display_name: Qwen 3 32B Direct Preference Optimization on GPU, 4K sequence length
elastic_policy:
  graceful_shutdown_timeout: 600
  is_elastic: false
  max_nodes: 16
  min_nodes: 1
  scaling_timeout: 600
  use_graceful_shutdown: true
instance_types:
- ml.p4de.24xlarge
- ml.p4d.24xlarge
- ml.p5.48xlarge
run:
  hf_access_token: null
  model_type: llm_finetuning_aws
  name: qwen-3-32b
  results_dir: ${base_results_dir}/${.name}
scale_config:
  1:
    trainer:
      num_nodes: 1
    training_config:
      training_args:
        learning_rate: 0.0002828
        micro_train_batch_size: 2
        train_batch_size: 128
  2:
    trainer:
      num_nodes: 2
    training_config:
      training_args:
        learning_rate: 0.0002828
        micro_train_batch_size: 2
        train_batch_size: 128
  4:
    trainer:
      num_nodes: 4
    training_config:
      training_args:
        learning_rate: 0.0002828
        micro_train_batch_size: 2
        train_batch_size: 128
  8:
    trainer:
      num_nodes: 8
    training_config:
      training_args:
        learning_rate: 0.0002828
        micro_train_batch_size: 2
        train_batch_size: 128
  16:
    trainer:
      num_nodes: 16
    training_config:
      training_args:
        learning_rate: 0.0002828
        train_batch_size: 128
trainer:
  devices: 8
  num_nodes: 1
training_config:
  datasets:
    preprocessor_cfgs:
    - key_map:
        chosen: chosen
        rejected: rejected
      prompt_key: prompt
      type: TrainingPOSampleConverter
    - type: ApplyChatTemplate
    - selected_columns:
      - prompt
      - chosen
      - rejected
      type: SelectColumns
    - add_special_tokens: false
      max_completion_length: 2048
      max_prompt_length: 2048
      type: TokenizeSampleDPO
    - max_seq_length: 8192
      tokens_labels:
      - chosen_input_ids
      type: SequenceLengthFilter
    - max_seq_length: 8192
      tokens_labels:
      - rejected_input_ids
      type: SequenceLengthFilter
    save_intermediate_processing_steps: false
    train_data:
      file_path: ''
      limit: null
      name: ''
    train_val_split_ratio: 0.9
    train_val_split_seed: 42
    val_data:
      file_path: ''
      limit: null
      name: ''
  force_rerun: false
  mlflow:
    run_id: ''
    tracking_uri: ''
  model_config:
    apply_chat_template: false
    attn_implementation: sdpa
    chat_template_key: null
    device_map: null
    generation_cfg:
      do_sample: true
      max_new_tokens: 2048
      num_parallel_jobs: 0
      num_return_sequences: 1
      temperature: 0.6
      tensor_parallel_size: 2
      top_p: 0.9
    lora_checkpoint_file_path: null
    model_name_or_path: Qwen/Qwen3-32B
    model_save_name: SageMaker/Qwen3-32B-Lora
    multimodal: false
    peft_config:
      bias: none
      lora_alpha: 32
      lora_dropout: 0.05
      peft_type: lora
      r: 16
      target_modules: all-linear
      task_type: CAUSAL_LM
      use_dora: false
  training_args:
    M: 1
    adam_betas:
    - 0.9
    - 0.95
    aux_loss_coef: 0
    beta: 0.01
    disable_ds_ckpt: false
    disable_fast_tokenizer: false
    eval_steps: -1
    grad_accum_dtype: null
    gradient_checkpointing: true
    gradient_checkpointing_use_reentrant: false
    gradient_clipping: true
    gradient_clipping_threshold: 1.0
    l2: 0.0
    label_smoothing: 0.0
    learning_rate: 0.0001
    load_checkpoint: true
    logging_steps: 1
    loss_type: sigmoid
    lr_scheduler: cosine
    lr_warmup_ratio: 0.1
    max_ckpt_mem: 100000000.0
    max_ckpt_num: 3
    max_epochs: 3
    max_len: 4096
    max_norm: 1.0
    max_samples: 100000000.0
    merge_weights: true
    micro_train_batch_size: 1
    nll_loss_coef: 0.0
    override_training_dir: true
    packing_samples: false
    pretrain_mode: false
    ref_offload: false
    reference_free: false
    resume_checkpoint_path: ''
    ring_attn_size: 1
    ring_head_stride: 1
    sampling_method: mc
    save_hf_ckpt: true
    save_steps: 0
    seed: 42
    strategy:
      fsdp_config:
        auto_wrap_policy: TRANSFORMER_BASED_WRAP
        backward_prefetch: BACKWARD_PRE
        cpu_offload: false
        cpu_ram_efficient_loading: true
        forward_prefetch: false
        sharding_strategy: HYBRID_SHARD
        state_dict_type: SHARDED_STATE_DICT
        sync_module_states: true
        use_orig_params: true
    train_batch_size: 16
    trainer_callbacks:
    - _target_: metering_callback.MeteringCallback
      output_path: /opt/ml/metering
    trainer_type: dpo
    training_dir: ''
    use_tensorboard: logs
    use_wandb: null
    weight_decay: 0.0
version: 2.1.1
