run:
  data_s3_path: s3://<bucket>/<data file>
  model_name_or_path: nova-lite-2/prod
  model_type: amazon.nova-2-lite-v1:0:256k
  name: my-rft-run
  replicas: 4
  reward_lambda_arn: arn:aws:lambda:<region>:<account-id>:function:<function-name>
training_config:
  global_batch_size: 64
  max_length: 8192
  reasoning_effort: high
  rollout:
    advantage_strategy:
      number_generation: 2
    generator:
      max_new_tokens: 6000
      set_random_seed: true
      temperature: 1
      top_k: 1
    rewards:
      api_endpoint:
        lambda_arn: arn:aws:lambda:<region>:<account-id>:function:<function-name>
        lambda_concurrency_limit: 12
  trainer:
    ent_coeff: 0.0
    kl_loss_coef: 0.001
    max_steps: 5
    optim_config:
      adam_beta1: 0.9
      adam_beta2: 0.95
      lr: 0.0001
      weight_decay: 0.0
    peft:
      lora_tuning:
        alpha: 32
        lora_plus_lr_ratio: 64.0
      peft_scheme: lora
    save_steps: ${oc.select:training_config.trainer.max_steps}
