defaults:
  - /hydra_config/verl-0.7.0/sft/default
  - /hydra_config/verl-0.7.0/sft/data/default
  - /hydra_config/verl-0.7.0/model/hf_model
  - /hydra_config/verl-0.7.0/engine/fsdp
  - /hydra_config/verl-0.7.0/optim/fsdp
  - /hydra_config/verl-0.7.0/sft/trainer/default
  - /hydra_config/verl-0.7.0/profiler/profiler
  - /hydra_config/verl-0.7.0/sft/checkpoint/default
  - /hydra_config/verl-0.7.0/sft/peft/lora
  - /hydra_config/verl-0.7.0/sft/model_config/qwen-3-8b
  - _self_

display_name: "Qwen 3 8B SFT Fine-Tuning with LoRA"
version: "1.0.0"
instance_types: ["ml.p5.48xlarge", "ml.p4de.24xlarge", "ml.p4d.24xlarge"]

run:
  name: qwen-3-8b

trainer:
  num_nodes: 1

training_config:
  data:
    train_batch_size: 32
    micro_batch_size_per_gpu: 4
    max_length: 4096
    max_token_len_per_gpu: 65536
    ignore_input_ids_mismatch: true
  model:
    lora_rank: 8
    target_modules: all-linear
  optim:
    lr: 2.0e-4
    weight_decay: 0.001
  engine:
    ulysses_sequence_parallel_size: 2
    strategy: fsdp2
    forward_prefetch: true
    model_dtype: bf16
  trainer:
    project_name: verl_sft_qwen3_8b_lora
    experiment_name: verl-sft-qwen-3-8b-lora
    total_epochs: 1
    save_freq: 4000
    max_ckpt_to_keep: 1
    logger:
    - console
