# @package recipes.training_config.algorithm
_target_: verl.trainer.config.AlgoConfig
gamma: 1.0
lam: 1.0
adv_estimator: grpo
norm_adv_by_std_in_grpo: true
use_kl_in_reward: false
kl_penalty: kl
kl_ctrl:
  _target_: verl.trainer.config.KLControlConfig
  type: fixed
  kl_coef: 0.001
  horizon: 10000
  target_kl: 0.1
use_pf_ppo: false
pf_ppo:
  reweight_method: pow
  weight_pow: 2.0
