defaults:
  - /hydra_config/llmft/default
  - /hydra_config/llmft/model_config/llama-3-1-8b-instruct
  - /hydra_config/llmft/peft/lora
  - /hydra_config/llmft/algorithm/sft
  - /hydra_config/llmft/datasets/default_sft
  - /hydra_config/llmft/strategy/fsdp_peft
  - _self_

display_name: "Llama 3.1 8B Supervised Fine-Tuning with LoRA on GPU, 4K sequence length"
version: "1.1.0"
instance_types: ['ml.p4de.24xlarge', 'ml.p4d.24xlarge', 'ml.p5.48xlarge', 'ml.g5.48xlarge']

run:
  name: llama-3-1-8b-instruct

training_config:
  model_config:
    model_name_or_path: "meta-llama/Llama-3.1-8B-Instruct"
    model_save_name: SageMaker/llama-3.1-8B-Instruct-Lora
    chat_template_key: llama--meta-llama-3.1-8b-instruct
  datasets:
    preprocessor_cfgs:
      - type: TrainingSFTSampleConverter
      - type: Seq2SeqTokensProcessor
        chat_template_name: llama_3_2_seq_instruct.jinja
        ignore_prompt_labels: true
      - type: DropColumns
        column_names:
          - messages
  training_args:
    merge_weights: true

elastic_policy:
  is_elastic: false
  min_nodes: 1
  max_nodes: 16
  use_graceful_shutdown: true
  scaling_timeout: 600
  graceful_shutdown_timeout: 600

scale_config:
  1:
    trainer:
      num_nodes: 1
    training_config:
      training_args:
        train_batch_size: 128
        micro_train_batch_size: 8
        learning_rate: 0.0004
  2:
    trainer:
      num_nodes: 2
    training_config:
      training_args:
        train_batch_size: 128
        micro_train_batch_size: 8
        learning_rate: 0.0004
  3:
    trainer:
      num_nodes: 3
    training_config:
      training_args:
        train_batch_size: 128
        learning_rate: 0.0004
        uneven_batch:
          use_uneven_batch: true
          num_dp_groups_with_small_batch_size: 16
          small_local_batch_size: 5
          large_local_batch_size: 6
  4:
    trainer:
      num_nodes: 4
    training_config:
      training_args:
        train_batch_size: 128
        micro_train_batch_size: 4
        learning_rate: 0.0004
  6:
    trainer:
      num_nodes: 6
    training_config:
      training_args:
        train_batch_size: 128
        learning_rate: 0.0004
        uneven_batch:
          use_uneven_batch: true
          num_dp_groups_with_small_batch_size: 16
          small_local_batch_size: 2
          large_local_batch_size: 3
  8:
    trainer:
      num_nodes: 8
    training_config:
      training_args:
        train_batch_size: 128
        micro_train_batch_size: 2
        learning_rate: 0.0004
  16:
    trainer:
      num_nodes: 16
    training_config:
      training_args:
        train_batch_size: 128
        learning_rate: 0.0004
