defaults:
  - /hydra_config/verl/default
  - /hydra_config/verl/algorithm/grpo
  - /hydra_config/verl/actor/default
  - /hydra_config/verl/ref/default
  - /hydra_config/verl/critic/default
  - /hydra_config/verl/rollout/vllm
  - /hydra_config/verl/actor_rollout_ref/default
  - /hydra_config/verl/trainer/default
  - /hydra_config/verl/data/default
  - /hydra_config/verl/reward_model/default
  - /hydra_config/verl/ray_cluster/default
  - /hydra_config/verl/peft/lora
  - /hydra_config/verl/reward/rlvr
  - /hydra_config/verl/model_config/llama-3-1-8b-instruct
  - _self_

display_name: "Llama 3.1 8B GRPO RLVR Fine-Tuning"
version: "1.1.0"
instance_types: ["ml.p5.48xlarge", "ml.p4de.24xlarge"]

run:
  name: verl-grpo-llama-3-dot-1-8b-instruct-lora
trainer:
  num_nodes: 1

training_config:
  actor_rollout_ref:
    actor:
      optim:
        lr: 1.0e-05
    rollout:
      enable_chunked_prefill: true
      layered_summon: false
      merge_lora_for_inference: false
    model:
      attn_implementation: null
      is_saving_checkpoint_in_lora: true
  trainer:
    project_name: grpo_example_gsm8k
    experiment_name: llama3_1_8b_grpo_lora
    logger:
    - console
    - mlflow
    resume_mode: resume_path
    resume_from_path: ''
  critic:
    model:
      fsdp_config:
        param_offload: true
    ppo_max_token_len_per_gpu: 24576
  custom_reward_function:
    lambda_arn: ''
    path: ''
    name: ''
