import logging
import os
from unittest.mock import patch

import pytest
from omegaconf import OmegaConf
from pydantic import ValidationError

from main import main

logger = logging.getLogger(__name__)


from tests.test_utils import (
    compare_artifacts,
    create_temp_directory,
    make_hydra_cfg_instance,
    mock_load_hosting_config,
)

# Test parameters for PPO and GRPO artifacts
VERL_TEST_PARAMS = [
    {
        "training_type": "grpo",
        "recipe": "fine-tuning/llama/verl-grpo-rlaif-llama-3-dot-2-1b-instruct-lora",
        "actual_dir_name": "verl-grpo-llama-3-dot-2-1b-instruct-lora",
    }
]

VERL_LAUNCH_JSON_TEST_PARAMS = [
    {
        "training_type": "grpo",
        "recipe": "fine-tuning/llama/verl-grpo-rlvr-llama-3-dot-1-8b-instruct-lora",
        "actual_dir_name": "verl-grpo-llama-3-dot-1-8b-instruct-lora",
    }
]


def compare_ray_verl_recipe_k8s_artifacts(artifacts_dir, actual_dir_name, training_type):
    logger.info(f"Comparing ray {training_type.upper()} recipe k8s artifacts")

    # Only check for files that are actually generated by Ray k8s workflow
    artifacts_paths = [
        f"/{actual_dir_name}/k8s_template/Chart.yaml",
        f"/{actual_dir_name}/k8s_template/values.yaml",
        f"/{actual_dir_name}/k8s_template/templates/training.yaml",
        f"/{actual_dir_name}/k8s_template/templates/training-config.yaml",
        f"/{actual_dir_name}/k8s_template/verl_config.yaml",
    ]

    k8s_baseline_artifacts_path = "/tests/ray_k8s_workflow/k8s_baseline_artifacts"
    compare_artifacts(artifacts_paths, artifacts_dir, k8s_baseline_artifacts_path)


@pytest.mark.parametrize("test_params", VERL_TEST_PARAMS)
def test_ray_verl_recipe_generates_ray_templates(test_params):
    """Test Ray VERL recipe generates Ray-specific templates"""
    training_type = test_params["training_type"]
    recipe = test_params["recipe"]
    actual_dir_name = test_params["actual_dir_name"]

    logger.info(f"Testing Ray {training_type.upper()} recipe generates Ray templates")

    artifacts_dir = create_temp_directory()
    overrides = [
        "instance_type=p5.48xlarge",
        f"recipes={recipe}",
        "base_results_dir={}".format(artifacts_dir),
        "container=test_container",
        "cluster=k8s",
        "cluster_type=k8s",
        "+env_vars.NEMO_LAUNCHER_DEBUG=1",
        "git.repo_url_or_path=https://github.com/aws/sagemaker-hyperpod-training-adapter-for-nemo.git",
        "git.branch=test_branch",
        "git.commit=test_commit",
        "git.token=test_token",
        f"++recipes.training_config.algorithm.adv_estimator={training_type}",
    ]

    sample_recipe_k8s_config = make_hydra_cfg_instance("../recipes_collection", "config", overrides)

    logger.info(f"\nsample_recipe_k8s_config for {training_type.upper()}\n")
    logger.info(OmegaConf.to_yaml(sample_recipe_k8s_config))

    main(sample_recipe_k8s_config)

    # Just verify that Ray-specific files are generated
    expected_files = [
        f"{artifacts_dir}/{actual_dir_name}/k8s_template/Chart.yaml",
        f"{artifacts_dir}/{actual_dir_name}/k8s_template/values.yaml",
        f"{artifacts_dir}/{actual_dir_name}/k8s_template/templates/training.yaml",
        f"{artifacts_dir}/{actual_dir_name}/k8s_template/templates/training-config.yaml",
    ]

    for file_path in expected_files:
        assert os.path.exists(file_path), f"Expected file not found: {file_path}"


@pytest.mark.parametrize("test_params", VERL_TEST_PARAMS)
def test_ray_verl_recipe_k8s_workflow(test_params):
    """Test Ray VERL recipe generates correct K8s artifacts"""
    training_type = test_params["training_type"]
    recipe = test_params["recipe"]
    actual_dir_name = test_params["actual_dir_name"]

    logger.info(f"Testing Ray {training_type.upper()} recipe k8s workflow")

    artifacts_dir = create_temp_directory()
    overrides = [
        "instance_type=ml.p4de.24xlarge",
        f"recipes={recipe}",
        "base_results_dir={}".format(artifacts_dir),
        "container=test_container",
        "cluster=k8s",
        "cluster_type=k8s",
        "+env_vars.NEMO_LAUNCHER_DEBUG=1",
        "git.repo_url_or_path=https://github.com/aws/sagemaker-hyperpod-training-adapter-for-nemo.git",
        "git.branch=test_branch",
        "git.commit=test_commit",
        "git.token=test_token",
        f"++recipes.training_config.algorithm.adv_estimator={training_type}",
    ]

    sample_recipe_k8s_config = make_hydra_cfg_instance("../recipes_collection", "config", overrides)

    logger.info(f"\nsample_recipe_k8s_config for {training_type.upper()}\n")
    logger.info(OmegaConf.to_yaml(sample_recipe_k8s_config))

    main(sample_recipe_k8s_config)

    compare_ray_verl_recipe_k8s_artifacts(artifacts_dir, actual_dir_name, training_type)


@pytest.mark.parametrize("test_params", VERL_LAUNCH_JSON_TEST_PARAMS)
@patch(
    "launcher.recipe_templatization.base_recipe_template_processor.BaseRecipeTemplateProcessor.load_hosting_config",
    side_effect=mock_load_hosting_config,
)
def test_ray_verl_recipe_k8s_workflow_with_launch_json(mock_load_hosting, test_params):
    """Test Ray VERL recipe k8s workflow with launch_json"""
    training_type = test_params["training_type"]
    recipe = test_params["recipe"]
    actual_dir_name = test_params["actual_dir_name"]

    logger.info(f"Testing Ray {training_type.upper()} recipe k8s workflow with launch_json")

    artifacts_dir = create_temp_directory(f"test_ray_verl_recipe_k8s_workflow_with_launch_json_{training_type}")

    overrides = [
        f"recipes={recipe}",
        "instance_type=ml.p4de.24xlarge",
        "base_results_dir={}".format(artifacts_dir),
        "container=test_container",
        "cluster=k8s",
        "cluster_type=k8s",
        "git.use_default=false",
        "git.entry_script=/app/src/train_hp.py",
        f"++recipes.training_config.algorithm.adv_estimator={training_type}",
    ]

    sample_recipe_k8s_config = make_hydra_cfg_instance("../recipes_collection", "config", overrides)
    OmegaConf.set_struct(sample_recipe_k8s_config, False)
    sample_recipe_k8s_config.cluster.persistent_volume_claims = [{"claimName": "fsx-claim", "mountPath": "/data"}]
    sample_recipe_k8s_config.launch_json = True

    logger.info(f"\nsample_recipe_k8s_config for {training_type.upper()} with launch_json\n")
    logger.info(OmegaConf.to_yaml(sample_recipe_k8s_config))

    del sample_recipe_k8s_config["hydra"]
    main(sample_recipe_k8s_config)

    artifacts_paths = [
        f"/{actual_dir_name}/k8s_template/launch.json",
        f"/{actual_dir_name}/k8s_template/values.yaml",
        f"/{actual_dir_name}/k8s_template/Chart.yaml",
        f"/{actual_dir_name}/k8s_template/templates/training.yaml",
        f"/{actual_dir_name}/k8s_template/templates/training-config.yaml",
        f"/{actual_dir_name}/k8s_template/verl_config.yaml",
    ]

    k8s_baseline_artifacts_path = "/tests/ray_k8s_workflow/k8s_baseline_artifacts"
    compare_artifacts(artifacts_paths, artifacts_dir, k8s_baseline_artifacts_path)


@pytest.mark.parametrize("test_params", VERL_TEST_PARAMS)
def test_ray_verl_recipe_k8s_workflow_invalid(test_params):
    """Test Ray VERL recipe validation works"""
    training_type = test_params["training_type"]
    recipe = test_params["recipe"]

    logger.info(f"Testing Ray {training_type.upper()} validation workflow")

    artifacts_dir = create_temp_directory()
    overrides = [
        "instance_type=p5.48xlarge",
        f"recipes={recipe}",
        "base_results_dir={}".format(artifacts_dir),
        "container=test_container",
        "cluster=k8s",
        "cluster_type=k8s",
        "+env_vars.NEMO_LAUNCHER_DEBUG=1",
        "git.repo_url_or_path=https://github.com/aws/sagemaker-hyperpod-training-adapter-for-nemo.git",
        "git.branch=test_branch",
        "git.commit=test_commit",
        "git.token=test_token",
        f"++recipes.algorithm.adv_estimator={training_type}",
        "++recipes.critic.ppo_micro_batch_size_per_gpu=0",
    ]

    sample_recipe_k8s_config = make_hydra_cfg_instance("../recipes_collection", "config", overrides)

    logger.info(f"\nsample_recipe_k8s_config for {training_type.upper()}\n")
    logger.info(OmegaConf.to_yaml(sample_recipe_k8s_config))

    with pytest.raises(ValidationError):
        main(sample_recipe_k8s_config)
