callbacks:
- _target_: nemo.utils.exp_manager.TimingCallback
- _target_: nemo.lightning.pytorch.callbacks.GarbageCollectionCallback
  gc_interval_train: 100
  gc_interval_val: 100
- _target_: nemo.lightning.pytorch.callbacks.megatron_comm_overlap.MegatronCommOverlapCallback
  tp_comm_overlap: false
- _target_: hyperpod_checkpointless_training.nemo_plugins.fault_injection.HPFaultInjectionCallback
  test_fault_config:
    fault_prob_after_bwd: 0
    fault_prob_between_lock: 0
    fault_prob_during_bwd: 0
    fault_prob_during_fwd: 0
    fault_prob_random: 0
    fault_ranks:
    - 8
    fault_type: ipr
    steps_before_fault: 3
- _target_: hyperpod_checkpointless_training.nemo_plugins.callbacks.CheckpointlessCallback
  clean_tensor_hook: true
  enable_checkpointless: true
  enable_checksum: false
  enable_inprocess: true
- _target_: hyperpod_checkpointless_training.nemo_plugins.datamodule_epoch_callback.DataModuleEpochCallback
data:
  global_batch_size: 512
  micro_batch_size: 1
  seq_length: 2048
dataset:
  dataset_path: null
  drop_last: true
  keep_in_memory: true
  num_workers: 1
  partition: train
  pin_memory: false
  shuffle: false
ddp:
  average_in_collective: true
  check_for_nan_in_grad: true
  grad_reduce_in_fp32: true
  overlap_param_gather: true
display_name: HyperPod Checkpointless Training Llama 3 70B Pre-Training on GPU, 2K
  sequence length
exp_manager:
  exp_dir: null
  name: experiment
instance_types:
- ml.p5.48xlarge
- ml.p5e.48xlarge
log:
  _target_: nemo.lightning.nemo_logger.NeMoLogger
  ckpt:
    _target_: nemo.lightning.pytorch.callbacks.model_checkpoint.ModelCheckpoint
    dirpath: ${recipes.log_dir}
    every_n_train_steps: 20
    filename: '{model_name}--{val_loss:.2f}-{step}-{consumed_samples}'
    mode: max
    monitor: step
    save_last: true
    save_optim_on_train_end: true
    save_top_k: 2
    save_weights_only: false
  log_dir: ${recipes.log_dir}
  name: llama3_70b_checkpointless_pretraining
  tensorboard:
    _target_: lightning.pytorch.loggers.TensorBoardLogger
    name: llama3_70b_checkpointless_pretraining
    save_dir: tb_logs
  wandb: null
log_dir: null
mmap:
  cache_dir: /dev/shm/pdl_cache
  checkpoint_frequency: 20
  lookback_length: 10
  prefetch_length: 10
model:
  config:
    seq_length: 2048
    vocab_size: 128256
optim:
  config:
    _target_: megatron.core.optimizer.OptimizerConfig
    adam_beta1: 0.9
    adam_beta2: 0.95
    adam_eps: 1.0e-05
    bf16: true
    clip_grad: 1.0
    fp16: false
    lr: 0.0003
    optimizer: adam
    use_distributed_optimizer: true
    weight_decay: 0.1
  lr_scheduler:
    _target_: nemo.lightning.pytorch.optim.CosineAnnealingScheduler
    constant_steps: 0
    min_lr: 3.0e-05
    warmup_steps: 2000
plugins:
  _target_: nemo.lightning.pytorch.plugins.MegatronMixedPrecision
  precision: bf16-mixed
pre_script: sysctl -w net.ipv4.ip_local_port_range='20000 65535'; export LD_LIBRARY_PATH='/opt/aws-ofi-nccl/lib:$LD_LIBRARY_PATH';
  ln -sf /opt/aws-ofi-nccl/lib/libnccl-net-ofi.so /opt/aws-ofi-nccl/lib/libnccl-net-aws-ofi.so
resources:
  hugepages: 5120Mi
  memory: 32000Mi
resume:
  _target_: hyperpod_checkpointless_training.nemo_plugins.resume.CheckpointlessAutoResume
  resume_from_directory: ${recipes.log.ckpt.dirpath}
  resume_if_exists: true
  resume_ignore_no_checkpoint: true
  resume_past_end: true
run:
  model_type: hyperpod_checkpointless_nemo
  name: llama-3-3-70b
  results_dir: ${base_results_dir}/${.name}
  time_limit: 6-00:00:00
strategy:
  ckpt_async_save: true
  ckpt_parallel_load: true
  context_parallel_size: 1
  gradient_as_bucket_view: true
  num_distributed_optimizer_instances: 2
  pipeline_dtype: torch.bfloat16
  pipeline_model_parallel_size: 4
  sequence_parallel: true
  tensor_model_parallel_size: 8
  virtual_pipeline_model_parallel_size: null
trainer:
  accelerator: gpu
  accumulate_grad_batches: 1
  devices: 8
  limit_test_batches: 50
  limit_val_batches: 32
  log_every_n_steps: 10
  max_steps: 1168251
  num_nodes: 16
  num_sanity_val_steps: 0
  reload_dataloaders_every_n_epochs: 1
  use_distributed_sampler: false
  val_check_interval: 2000
version: 2.1.1
