run:
  data_s3_path: s3://my-bucket-name/train.jsonl
  mlflow_experiment_name: my-full-rank-sft-experiment
  mlflow_run_name: my-full-rank-sft-run
  mlflow_tracking_uri: ''
  model_name_or_path: nova-lite-2/prod
  model_type: amazon.nova-2-lite-v1:0:256k
  name: my-full-rank-sft-run
  output_s3_path: s3://my-bucket-name/outputs/
  replicas: 4
training_config:
  global_batch_size: 32
  lr_scheduler:
    min_lr: 1.0e-06
    warmup_steps: 15
  max_length: 32768
  max_steps: 100
  optim_config:
    adam_beta1: 0.9
    adam_beta2: 0.95
    lr: 1.0e-05
    weight_decay: 0.0
  peft:
    peft_scheme: 'null'
  reasoning_enabled: true
  save_steps: ${oc.select:training_config.max_steps}
  save_top_k: 5
