run:
  data_s3_path: ''
  mlflow_experiment_name: my-cpt-experiment
  mlflow_run_name: my-cpt-run
  mlflow_tracking_uri: ''
  model_name_or_path: nova-micro/prod
  model_type: amazon.nova-micro-v1:0:128k
  name: my-cpt-run
  output_s3_path: ''
  replicas: 8
training_config:
  global_batch_size: 256
  max_length: 8192
  model:
    attention_dropout: 0.0
    ffn_dropout: 0.0
    hidden_dropout: 0.0
    optim:
      adam_w_mode: true
      betas:
      - 0.9
      - 0.999
      eps: 1.0e-06
      lr: 1.0e-05
      name: distributed_fused_adam
      sched:
        constant_steps: 0
        min_lr: 1.0e-06
        warmup_steps: 10
      weight_decay: 0.0
  trainer:
    max_epochs: 1
