run:
  data_s3_path: ''
  mlflow_experiment_name: my-lora-experiment
  mlflow_run_name: my-lora-run
  mlflow_tracking_uri: ''
  model_name_or_path: nova-pro/prod
  model_type: amazon.nova-pro-v1:0:300k
  name: my-lora-run
  output_s3_path: ''
  replicas: 6
training_config:
  global_batch_size: 32
  max_length: 16384
  model:
    attention_dropout: 0.0
    dpo_cfg:
      beta: 0.1
    ffn_dropout: 0.0
    hidden_dropout: 0.0
    optim:
      adam_w_mode: true
      betas:
      - 0.9
      - 0.999
      eps: 1.0e-08
      lr: 1.0e-05
      name: distributed_fused_adam
      sched:
        constant_steps: 0
        min_lr: 1.0e-06
        warmup_steps: 10
      weight_decay: 0.01
    peft:
      lora_tuning:
        adapter_dropout: 0.01
        alpha: 64
        loraplus_lr_ratio: 20.0
      peft_scheme: lora
  trainer:
    max_epochs: 2
