{{- $root := .Values }}
{{ $config := .Values.trainingConfig }}

apiVersion: kubeflow.org/v1
kind: PyTorchJob
metadata:
  name: {{ $config.jobName }}
  namespace: {{ $config.namespace }}
  {{- if $config.customLabels }}
  labels:
    {{- range $key, $value := $config.customLabels }}
    {{ $key | quote }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
  {{- if $config.annotations }}
  annotations:
    {{- range $key, $value := $config.annotations }}
    {{ $key | quote }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
spec:
  runPolicy:
    cleanPodPolicy: None
  pytorchReplicaSpecs:
    Master:
      replicas: 1
      restartPolicy: OnFailure
      template:
        metadata:
          labels:
            workload-type: "gpu-intensive-{{ .Values.trainingConfig.jobName }}"
        spec:
          affinity:
            podAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 100
                podAffinityTerm:
                  labelSelector:
                    matchExpressions:
                    - key: workload-type
                      operator: In
                      values: ["gpu-intensive-{{ .Values.trainingConfig.jobName }}"]
                  topologyKey: kubernetes.io/hostname
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                  - key: workload-type
                    operator: In
                    values: ["cpu-only-{{ .Values.trainingConfig.jobName }}"]
                topologyKey: kubernetes.io/hostname
            {{- if (or $config.labelSelector.required $config.labelSelector.preferred) }}
            nodeAffinity:
              {{- if $config.labelSelector.required }}
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                    {{- range $key, $values := $config.labelSelector.required }}
                    - key: {{ $key | quote }}
                      operator: In
                      values:
                        {{- range $values }}
                        - {{ . | quote }}
                        {{- end}}
                    {{- end }}
              {{- end }}
              {{- if $config.labelSelector.preferred }}
              {{- $index := 0 }}
              preferredDuringSchedulingIgnoredDuringExecution:
                {{- range $key, $values := $config.labelSelector.preferred }}
                - weight: {{ index $config.labelSelector.weights $index }}
                  preference:
                    matchExpressions:
                      - key: {{ $key | quote }}
                        operator: In
                        values:
                          {{- range $values }}
                          - {{ . | quote }}
                          {{- end }}
                {{- $index = add $index 1 }}
                {{- end }}
              {{- end }}
            {{- end }}
          tolerations:
            {{- range $config.requiredTolerations }}
            - key: {{ .key }}
              operator: {{ .operator }}
              value: {{ .value }}
              effect: {{ .effect }}
            {{- end }}
          serviceAccountName: {{ $config.serviceAccountName }}
          containers:
            - name: pytorch
              {{- if $root.image.trainingImage }}
              image: {{ $root.image.trainingImage }}
              {{- else }}
              image: "placeholder:latest"
              {{- end }}
              imagePullPolicy: Always
              resources:
                {{- toYaml $config.training.resources.master | nindent 16 }}
              env:
                - name: SVC_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.labels['training.kubeflow.org/job-name']
                - name: NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: INSTANCE_TYPE
                  value: {{ $config.training.instanceType | quote }}
              volumeMounts:
                - name: fsx-path-main
                  mountPath: /sagemaker/fsx/main
                - mountPath: /config
                  name: training-config
                - mountPath: /dev/shm
                  name: dshm
                - mountPath: /var/log/aws/clusters
                  name: logs
                - mountPath: /sagemaker/fsx/output_artifacts
                  name: fsx-path-output-artifacts
          volumes:
            - name: fsx-path-main
              hostPath:
                path: /sagemaker/fsx/main
                type: DirectoryOrCreate
            - name: fsx-path-init
              hostPath:
                path: /sagemaker/fsx/init
                type: DirectoryOrCreate
            - name: training-config
              configMap:
                name: {{ $config.jobName }}-training-config
            - name: dshm
              emptyDir:
                medium: Memory
            - name: logs
              hostPath:
                path: /var/log/aws/clusters
                type: DirectoryOrCreate
            - name: fsx-path-output-artifacts
              hostPath:
                path: /sagemaker/fsx/output_artifacts
                type: DirectoryOrCreate
    Worker:
      replicas: {{ $config.training.worker_replicas }}
      restartPolicy: OnFailure
      template:
        metadata:
          labels:
            workload-type: "gpu-intensive-{{ .Values.trainingConfig.jobName }}"
        spec:
          affinity:
            podAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 100
                podAffinityTerm:
                  labelSelector:
                    matchExpressions:
                    - key: workload-type
                      operator: In
                      values: ["gpu-intensive-{{ .Values.trainingConfig.jobName }}"]
                  topologyKey: kubernetes.io/hostname
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                  - key: workload-type
                    operator: In
                    values: ["cpu-only-{{ .Values.trainingConfig.jobName }}"]
                topologyKey: kubernetes.io/hostname
            {{- if (or $config.labelSelector.required $config.labelSelector.preferred) }}
            nodeAffinity:
              {{- if $config.labelSelector.required }}
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                    {{- range $key, $values := $config.labelSelector.required }}
                    - key: {{ $key | quote }}
                      operator: In
                      values:
                        {{- range $values }}
                        - {{ . | quote }}
                        {{- end}}
                    {{- end }}
              {{- end }}
              {{- if $config.labelSelector.preferred }}
              {{- $index := 0 }}
              preferredDuringSchedulingIgnoredDuringExecution:
                {{- range $key, $values := $config.labelSelector.preferred }}
                - weight: {{ index $config.labelSelector.weights $index }}
                  preference:
                    matchExpressions:
                      - key: {{ $key | quote }}
                        operator: In
                        values:
                          {{- range $values }}
                          - {{ . | quote }}
                          {{- end }}
                {{- $index = add $index 1 }}
                {{- end }}
              {{- end }}
            {{- end }}
          tolerations:
            {{- range $config.requiredTolerations }}
            - key: {{ .key }}
              operator: {{ .operator }}
              value: {{ .value }}
              effect: {{ .effect }}
            {{- end }}
          serviceAccountName: {{ $config.serviceAccountName }}
          containers:
            - name: pytorch
              {{- if $root.image.trainingImage }}
              image: {{ $root.image.trainingImage }}
              {{- else }}
              image: "placeholder:latest"
              {{- end }}
              imagePullPolicy: Always
              resources:
                {{- toYaml $config.training.resources.worker | nindent 16 }}
              securityContext:
                capabilities:
                  add: ["IPC_LOCK"]
              env:
                - name: SVC_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.labels['training.kubeflow.org/job-name']
                - name: NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: INSTANCE_TYPE
                  value: {{ $config.training.instanceType | quote }}
              volumeMounts:
                - name: fsx-path-main
                  mountPath: /sagemaker/fsx/main
                - mountPath: /config
                  name: training-config
                - mountPath: /dev/shm
                  name: dshm
                - mountPath: /var/log/aws/clusters
                  name: logs
                - mountPath: /sagemaker/fsx/output_artifacts
                  name: fsx-path-output-artifacts
          volumes:
            - name: fsx-path-main
              hostPath:
                path: /sagemaker/fsx/main
                type: DirectoryOrCreate
            - name: fsx-path-init
              hostPath:
                path: /sagemaker/fsx/init
                type: DirectoryOrCreate
            - name: training-config
              configMap:
                name: {{ $config.jobName }}-training-config
            - name: dshm
              emptyDir:
                medium: Memory
            - name: logs
              hostPath:
                path: /var/log/aws/clusters
                type: DirectoryOrCreate
            - name: fsx-path-output-artifacts
              hostPath:
                path: /sagemaker/fsx/output_artifacts
                type: DirectoryOrCreate
