# @package recipes
defaults:
  - /hydra_config/verl-0_7_0/sft/default
  - /hydra_config/verl-0_7_0/sft/data/default
  - /hydra_config/verl-0_7_0/model/hf_model
  - /hydra_config/verl-0_7_0/engine/fsdp
  - /hydra_config/verl-0_7_0/optim/fsdp
  - /hydra_config/verl-0_7_0/sft/trainer/default
  - /hydra_config/verl-0_7_0/profiler/profiler
  - /hydra_config/verl-0_7_0/sft/checkpoint/default
  - /hydra_config/verl-0_7_0/sft/peft/lora
  - _self_

version: 1.0.0

run:
  name: verl-sft-llama-3-dot-2-3b-instruct-lora

trainer:
  num_nodes: 1

training_config:
  data:
    train_batch_size: 64
    micro_batch_size_per_gpu: 8
    truncation: right
    ignore_input_ids_mismatch: true
    use_dynamic_bsz: true

  model:
    path: meta-llama/Llama-3.2-3B-Instruct
    trust_remote_code: false
    use_liger: true
    use_fused_kernels: false

  engine:
    strategy: fsdp2
    model_dtype: bf16
    forward_prefetch: true

  optim:
    lr: 2.0e-04
    weight_decay: 0.001
    betas: [0.9, 0.95]
    lr_scheduler_type: cosine

  trainer:
    project_name: verl_sft_llama_3_2_3b
    experiment_name: llama_3_2_3b_sft_fsdp_lora_tatqa
    total_epochs: 1
    max_ckpt_to_keep: 3
    resume_mode: resume_path
