name: Python Unit Test CI

on:
  pull_request:
    branches:
      - main # Change to the branch we want to target for PRs
  push:
    branches:
      - main # Triggers on direct pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive # Checkout submodules as well
          fetch-depth: 0 # Full history for diff-cover branch comparison

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # Set python version to 3.10

      - name: Install unit test dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir --no-deps sagemaker
          pip install -r requirements.txt
          pip install transformers diff-cover

      - name: Run unit tests
        run: |
          python -m pytest -vv

      - name: Check coverage on new lines
        if: github.event_name == 'pull_request'
        run: |
          diff-cover coverage.xml --compare-branch=origin/${{ github.base_ref }} --fail-under=90
