image:
  # training image
  trainingImage: cfg.container

  # image pulling policy
  pullPolicy: Always


trainingConfig:
  # current job name
  jobName: "nil"

  # namespace to launch job
  namespace: "default"

  # list of custom annotations apply to jobs
  annotations: null

  # list of custom labels apply to jobs and pods
  customLabels: null

  # Kueue scheduler priority class name
  priorityClassName: null

  # name of service account associated with the namespace
  serviceAccountName: null

  # number of GPUs to request
  devices: null

  # number of EFA devices if the instance type support EFA
  # Hardcoding to 32 as it provides better performance
  numEFADevices: 32

  # number of nodes to run
  master_nodes: 1
  worker_nodes: 0


  # restart policy
  restartPolicy: OnFailure

  # select preferred and required labels for nodes
  labelSelector:
    required: null # select nodes with required labels
    preferred: null # select nodes with priority which has preferred labels
    weights: null # list of weights for the preferred labels

  # The cleanup policy after the job completes or fails.
  cleanPodPolicy: null

  # init container to run before the main container
  initContainer:
    name: init-container
    image: null
    env: []
