distributed_backend: nccl
exp_manager:
  auto_checkpoint:
    enabled: false
  checkpoint_callback_params:
    every_n_train_steps: 10
    mode: max
    monitor: step
    save_last: false
    save_top_k: 0
  checkpoint_dir: ${recipes.exp_manager.exp_dir}/checkpoints/
  create_checkpoint_callback: true
  create_mlflow_logger: false
  create_tensorboard_logger: false
  create_wandb_logger: false
  exp_dir: null
  export_full_model:
    every_n_train_steps: 0
    save_last: true
  mlflow_logger_kwargs:
    tracking_uri: ${recipes.exp_manager.exp_dir}/mlflow
  name: experiment
  resume_from_checkpoint: null
  summary_writer_kwargs:
    save_dir: ${recipes.exp_manager.exp_dir}/tensorboard
  wandb_logger_kwargs:
    save_dir: ${recipes.exp_manager.exp_dir}
model:
  activation_checkpointing: true
  auto_wrap_policy: transformer_auto_wrap_policy
  backward_fetch_policy: backward_pre
  data:
    dataset_type: hf
    train_dir: null
    use_synthetic_data: false
    val_dir: null
    zipped_data: false
  do_finetune: false
  forward_prefetch: true
  grad_clip: 1.0
  hf_access_token: None
  hf_model_name_or_path: tiiuae/falcon-7b
  limit_all_gathers: true
  log_reduced_training_loss: true
  lr_decay_iters: 47683
  max_context_width: 2048
  model_type: falcon
  optim:
    betas:
    - 0.9
    - 0.98
    lr: 0.0002
    name: adamw
    sched:
      constant_steps: 0
      min_lr: 2.0e-05
      name: CosineAnnealing
      warmup_steps: 500
    weight_decay: 0.01
  peft:
    peft_type: null
  precision: bf16
  seed: 12345
  shard_degree: 16
  sharding_strategy: hybrid_shard
  train_batch_size: 1
  use_flash_attention: true
  use_orig_param: false
  val_batch_size: 1
  viztracer:
    enabled: false
run:
  model_type: hf
  name: falcon-7b
  results_dir: ${base_results_dir}/${.name}
  time_limit: 6-00:00:00
trainer:
  accelerator: gpu
  devices: 8
  limit_val_batches: 0
  log_every_n_steps: 10
  max_steps: 50
  num_nodes: 2
  precision: bf16
  val_check_interval: 1
use_smp_model: false
