defaults:
  - /hydra_config/verl-0_7_0/sft/default
  - /hydra_config/verl-0_7_0/dpo/data/default
  - /hydra_config/verl-0_7_0/model/hf_model
  - /hydra_config/verl-0_7_0/engine/fsdp
  - /hydra_config/verl-0_7_0/optim/fsdp
  - /hydra_config/verl-0_7_0/sft/trainer/default
  - /hydra_config/verl-0_7_0/dpo/trainer/default
  - /hydra_config/verl-0_7_0/profiler/profiler
  - /hydra_config/verl-0_7_0/sft/checkpoint/default
  - /hydra_config/verl-0_7_0/model_config/gemma-4-e4b-it
  - _self_

display_name: "Gemma 4 E4B IT DPO Full Fine-Tuning"
version: 2.0.1
instance_types: ["ml.p5.48xlarge", "ml.p4de.24xlarge"]

run:
  name: verl-dpo-gemma-4-e4b-it-fft

trainer:
  num_nodes: 1

training_config:
  data:
    train_batch_size: 64
    max_length: 16384
    max_token_len_per_gpu: 33280
    truncation: left
    micro_batch_size_per_gpu: 1

  model:
    use_liger: false
    use_fused_kernels: true
    tiled_mlp:
      enabled: false
      num_shards: 4

  engine:
    use_torch_compile: true
    model_dtype: bfloat16
    strategy: fsdp2
    dtype: bfloat16

  optim:
    lr: 5.0e-5
    weight_decay: 0.0
    lr_warmup_steps_ratio: 0.1
    min_lr_ratio: 0.1
    lr_scheduler_type: cosine

  trainer:
    beta: 0.01
    loss_type: sigmoid
    total_epochs: 2
    save_freq: after_each_epoch
    test_freq: 5
